# Site settings
title: Precipitate
header-img: img/home-bg.jpg
email: precipitate-info@readcoor.com
copyright_name: Precipitate Project
description: "The Precipitate Project tells you all about in-situ sequencing"
baseurl: ""
url: "http://precipitate.bio"
twitter_username: nobody
github_username:  nobody
email_username:  precipitate-info@readcoor.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
